#!/bin/bash

############################################################
##################### CONSTANTS ############################
############################################################

Timefile=".snapshot-timestamp"

indent() { sed 's/^/   /'; }
die()    { echo "Error: $1" >&2 ; exit $2; }
warn()   { echo "Warning: $1" >&2 ; }

############################################################

set -o pipefail -o nounset

Self=$(basename $0)

# long options to short ones
for arg in "$@"
do
    shift
    case "$arg" in
        "--dry-run")    set -- "$@" "-n" ;;
        "--verbose")    set -- "$@" "-v" ;;
        *)              set -- "$@" "$arg"
  esac
done

# defaults
Verbose=n
DryRun=n
# parse options
OPTIND=1
while getopts "nv" opt
do
    case "$opt" in
        "n") DryRun=y ;;
        "v") Verbose=y ;;
        "?") die "unknown option" 10 ;;
    esac
done
shift $(expr $OPTIND - 1) # remove options from positional parameters

# handle non-option arguments
[[ $# -gt 1 ]] && die "$Self: only one single configuration file can be provided." 12

############################################################

if [ $# -eq 1 ]
then
	[ -f "$1" -a -r "$1" ] || die "$Self: configuration file $1 not found or not readable." 20
	# source the job config
	source "$1"
	if [ -z ${Job+x} ]; then
		Job=$(basename -s .conf $1)
	fi
	Self="${Self}@${Job}"
fi

# check whether all mandatory variables were set in config file or environment
[ -z ${Job+x} ]			&& die "Job name (Job) is required." 21
[ -z ${DATABASES+x} ]		&& die "List of databases (DATABASES) is required." 21
[ -z ${DB_DUMP+x} ]		&& die "Dump utility (DB_DUMP) is required." 21
[ -z ${REMOTE_BASE+x} ]		&& die "Remote path (REMOTE_BASE) is required." 21
[ -z ${TAG+x} ]			&& die "Snapshot tag format (TAG) is required." 21

############################################################

Outdir="$(mktemp -d)" || die "Could not create temporary directory." 30

touch "${Outdir}/${Timefile}" || die "Cannot touch(1) timestamp file '${Outdir}/${Timefile}'" 31

chmod 0444 "${Outdir}/${Timefile}" || warn "Could not make timestamp file '${Outdir}/${Timefile}' read-only."

Timestamp="$(date ${TAG_OPTIONS:-} -r "${Outdir}/${Timefile}" +"${TAG}")"
[ -z "${Timestamp+x}" ] && die "Problem generating new snapshot tag." 32

# set defaults for optional variables
[ -z ${WORK_DIR+x} ]    && WORK_DIR=${Outdir}
[ -z ${DB_ARGS+x} ]     && DB_ARGS=""

echo "- Creating snapshots in ${Outdir}:"

[ -n "${DB_USER:+x}" ] && SUDO_CMD="sudo -u ${DB_USER:-}"

is_array() {
    [[ $# -ne 1 ]] && echo "is_array(): supply exactly one variable name as an argument" >&2 && return 2
    local var=$1
    [[ "$(declare -p "$var" 2> /dev/null)" =~ "declare -a" ]] && return 0 || return 1
}

for (( i=0; i<${#DATABASES[@]}; i++ ))
do
    Db=${DATABASES[$i]}
    # cd to working directory
	echo -n "  * ${Db}: cd"
    if is_array WORK_DIR
    then
        cd ${WORK_DIR[$i]} die " -- Failed to change directory to: ${WORK_DIR[$i]}" 41
    else
        cd ${WORK_DIR} die " -- Failed to change directory to: ${WORK_DIR}" 42
    fi
    # run dump
    if is_array DB_DUMP
    then
        DUMP_CMD=${DB_DUMP[$i]}
    else
        DUMP_CMD=${DB_DUMP}
    fi
    if is_array DB_ARGS
    then
        DUMP_ARGS=${DB_ARGS[$i]}
    else
        DUMP_ARGS=${DB_ARGS:-}
    fi
	echo -n " dump"
    ${SUDO_CMD:-} ${DUMP_CMD} ${DUMP_ARGS} "${Db}" > "${Outdir}/${Db}.sql" && echo -n " -- OK" || die " -- Database dump failed." 40

    echo
done

echo ; echo -n "- Copying to ${REMOTE_BASE}${Timestamp}:"

if [ "$DryRun"  = "n" ]
then
	rsync -a "${REMOTE_AUTH[@]:-}" "${Outdir}/" "${REMOTE_BASE}${Timestamp}"
else
	echo
	rsync -avn "${REMOTE_AUTH[@]:-}" "${Outdir}/" "${REMOTE_BASE}${Timestamp}"
fi

if [ $? -ne 0 ]
then
	echo " Error code: $?"
	die "rsync failed, retaining local files in ${Outdir}." 50
else
	echo " Done."
	echo -n "- Deleting temporary files:"

    cd "${Outdir}"
	for Db in ${DATABASES[@]}
	do
		rm -f "${Db}.sql" && echo -n " ${Db}.sql" || die "Could not delete ${Db}.sql." 60
	done

	rm -f "${Timefile}" && echo -n " ${Timefile}" || die "Could not delete ${Timefile}." 61

	cd /
	rmdir "${Outdir}" && echo -n " ${Outdir}" || die "Could not remove ${Outdir}." 62

	echo " Done."
fi

